-- 지역 생성(LOCATION)
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('KOREA', '전체시', '전체구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL01', '서울시', '강남구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL02', '서울시', '강동구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL03', '서울시', '강북구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL04', '서울시', '강서구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL05', '서울시', '관악구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL06', '서울시', '광진구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL07', '서울시', '구로구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL08', '서울시', '금천구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL09', '서울시', '노원구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL10', '서울시', '도봉구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL11', '서울시', '동대문구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL12', '서울시', '동작구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL13', '서울시', '마포구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL14', '서울시', '서대문구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL15', '서울시', '서초구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL16', '서울시', '성동구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL17', '서울시', '성북구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL18', '서울시', '송파구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL19', '서울시', '양천구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL20', '서울시', '영등포구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL21', '서울시', '용산구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL22', '서울시', '은평구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL23', '서울시', '종로구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL24', '서울시', '중구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('SEOUL25', '서울시', '중랑구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON01', '인천시', '강화군');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON02', '인천시', '계양구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON03', '인천시', '남동구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON04', '인천시', '동구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON05', '인천시', '미추홀구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON06', '인천시', '부평구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON07', '인천시', '서구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON08', '인천시', '연수구');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON09', '인천시', '옹진군');
INSERT INTO PARA.LOCATION(LOC_CODE, LOC_SIDO, LOC_SIGUNGU) VALUES('INCHEON10', '인천시', '중구');


-- 발주 상태 생성(PAO_STATUS)
INSERT INTO PARA.PAO_STATUS(PS_CODE, PS_NAME) VALUES(0, '발주 취소');
INSERT INTO PARA.PAO_STATUS(PS_CODE, PS_NAME) VALUES(1, '발주 대기');
INSERT INTO PARA.PAO_STATUS(PS_CODE, PS_NAME) VALUES(2, '발주 승인');
INSERT INTO PARA.PAO_STATUS(PS_CODE, PS_NAME) VALUES(3, '발주 완료');


-- 주문 상태 생성(ORDER_STATUS)
INSERT INTO PARA.ORDER_STATUS(OS_CODE, OS_NAME) VALUES(0, '환불');
INSERT INTO PARA.ORDER_STATUS(OS_CODE, OS_NAME) VALUES(1, '대기');
INSERT INTO PARA.ORDER_STATUS(OS_CODE, OS_NAME) VALUES(2, '제조');
INSERT INTO PARA.ORDER_STATUS(OS_CODE, OS_NAME) VALUES(3, '완료');


-- 관리자 계정 생성(ADMIN)
-- 초기 생성 시 메인 화면에서 비밀번호 찾기를 하고 이메일에서 확인한 비밀번호로 로그인하여 마이페이지에서 비밀번호 변경하여 사용
INSERT INTO PARA.ADMIN
(ADMIN_ID, ADMIN_PW, ADMIN_NAME, ADMIN_PHONE, ADMIN_EMAIL, LOC_CODE, AUTH, ADMIN_DELFLAG)
VALUES(0000, '0000', '관리자', '010-0000-0000', 'info.happy0612@gmail.com', 'KOREA', 'S', 'N');

-- 담당자 계정 생성(ADMIN)
-- 초기 생성 시 메인 화면에서 비밀번호 찾기를 하고 이메일에서 확인한 비밀번호로 로그인하여 마이페이지에서 비밀번호 변경하여 사용
INSERT INTO PARA.ADMIN
(ADMIN_ID, ADMIN_PW, ADMIN_NAME, ADMIN_PHONE, ADMIN_EMAIL, LOC_CODE, AUTH, ADMIN_DELFLAG)
VALUES(1111, '1111', '이영재', '010-1111-1111', 'info.happy0612@gmail.com', 'KOREA', 'S', 'N');


-- 메뉴 생성(MENU) --> 메뉴 생성은 담당자 계정으로 로그인하여 수동으로 해줘야 데이터가 화면에 적용 됨(para.dmp를 import하면 사용 가능)
INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '후라이드치킨', 18000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '양념치킨', 19000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '간장치킨', 19000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '스노윙치킨', 19000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '순살파닭', 20000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '불고기 피자', 19000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '베이컨 피자', 21000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '고르곤졸라 피자', 19000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '고구마 피자', 20000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '치즈추가', 2000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '피자 토핑 추가', 2000, '주메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '치즈스틱', 10000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '감자튀김', 12000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '새우튀김', 14000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '닭발', 15000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '소시지', 16000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '어묵탕', 17000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '짬뽕탕', 18000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '홍합탕', 16000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '먹태', 12000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '한치', 12000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '화채', 16000, '사이드메뉴', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '콜라', 2000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '칠성 사이다', 2000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '스프라이트', 2000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '환타', 2000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '마우틴듀', 2000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '웰치스', 2300, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '참이슬', 4500, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '처음처럼', 4500, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '좋은데이', 4000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '청하', 5000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '하이트', 4000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '카스', 4000, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '버드와이저', 3500, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '클라우드', 4500, '음료', 'N');

INSERT INTO PARA.MENU(MENU_SEQ, MENU_NAME, MENU_PRICE, MENU_CATEGORY, MENU_DELFLAG)
VALUES(MENU_SEQ.NEXTVAL, '카프리', 3500, '음료', 'N');


-- 품목 생성(ITEM)
INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '양념소스 2KG', 2000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '매운소스 2KG', 2200, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '달콤소스 2KG', 2100, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '마요네즈 2KG', 2500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '머스타드 2KG', 2500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '케첩 2KG', 2300, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '스노윙 가루 1KG', 2500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '소금 2KG', 2300, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '설탕 2KG', 2200, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '후추 500ml', 1000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '간장 2L', 1800, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '식초 2L', 1900, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '캡사이신 2L', 12000, 'Y');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '강냉이 1KG', 3000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '모짜렐라 치즈 1KG', 8000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '파마산 치즈 가루 2KG', 4000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '감자 1KG', 3000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '고구마 1KG', 3000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '어묵탕 10EA', 15000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '홍합탕 10EA', 10000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '짬뽕탕 10EA', 16000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '닭발 10EA', 20000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '화채 과일 10EA', 12000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '한치 10EA', 20000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '먹태 10EA', 23000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '피자 도우(Medium) 10EA', 10000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '피자 도우(Large) 10EA', 12000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '감자튀김 2KG', 5000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '새우튀김 2KG', 9000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '치즈스틱 2KG', 13000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '소시지 40EA', 9000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '간고기 2KG', 5000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '베이컨 1KG', 12000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '생닭 5KG', 9000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '정육 5KG', 7500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '정육 10KG', 15000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '쌀 10KG', 30000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '쌀 20KG', 60000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '대파 1KG', 2000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '양파 1KG', 5000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '당근 1KG', 5200, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '쌀 20KG', 60000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '우유 1.5L', 500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '콜라 250ml 30EA', 10000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '콜라 500ml 30EA', 20000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '칠성 사이다 500ml 30EA', 21000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '스프라이트 500ml 30EA', 19000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '환타 500ml 30EA', 20000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '웰치스 500ml 30EA', 25000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '마운틴듀 500ml 30EA', 20500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '참이슬 360ml 30EA', 28500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '처음처럼 360ml 30EA', 28300, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '좋은데이 360ml 30EA', 28000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '청하 300ml 30EA', 28500, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '하이트 맥주 640ml 30EA', 23000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '카스 맥주 640ml 30EA', 23000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '클라우드 맥주 640ml 30EA', 24000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '버드와이저 맥주 350ml 30EA', 21000, 'N');

INSERT INTO PARA.ITEM(ITEM_SEQ, ITEM_NAME, ITEM_PRICE, ITEM_DELFLAG)
VALUES(ITEM_SEQ.NEXTVAL, '카프리 맥주 350ml 30EA', 21200, 'N');


