

DELETE FROM TIMESHEET;



SELECT ALBA_SEQ, TS_SEQ, SUBSTR(TS_DATE, 0, 7) TS_DATE, TS_WORKHOUR, ALBA_NAME, ALBA_PHONE, ALBA_ADDRESS, 
		ALBA_TIMESAL, ALBA_BANK, ALBA_ACCOUNT, ALBA_DELFLAG, ALBA_REGDATE, STORE_CODE
	FROM TIMESHEET JOIN ALBA
		USING(ALBA_SEQ)
			WHERE SUBSTR(TS_DATE, 0, 7) = '2019-05';